<a href="https://colab.research.google.com/github/alexandrufrunza/Informatica-aplicata/blob/main/Laborator_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Generarea de vectori și matrice folosind NumPy
1.   Concatenarea
2.   Generarea vectorilor folosind metoda **arrange**
3.   Funcțiile **linspace** și **logspace**
4.   Funcțiile **zeros** și **ones** 
5.   Funcțiile **rand**, **randint** și **randn**
6.   Funcțiile **eye** și **identity**

# Funcții și operatori specifici lucrului cu vectori și matrice
1.   Înmulțirea element cu element și înmulțirea matriceală
2.   Funcțiile **dot**, **transpose** și **conj**/**conjugate**
3.   Funcția **len** și variabilele **shape** și **size**
4.   Funcțiile **min** și **max**
5.   Funcția **sort**
6.   Funcția **where**
7.   Funcțiile **rot90**, **fliplr** și **flipud**
8.   Funcțiile **det** și **inv**
9.   Funcția **diag**
10.  Funcțiile **tril** și **triu**
11.  Funcția **reshape**

# Scrierea și citirea din fișiere folosind NumPy




# Generarea de vectori și matrice folosind NumPy


In [ ]:
# Importarea librăriei NumPy
import numpy as np

# Generarea de vectori folosind NumPy
a_vec = np.array([2, 4, -5, 0])
print(a_vec)

# Generarea de matrici folosind NumPy
A_mat = np.array([ [2, 4, 0], [5, 7, -2], [12, 5, -4] ])
print(A_mat)

[ 2  4 -5  0]
[[ 2  4  0]
 [ 5  7 -2]
 [12  5 -4]]


## Concatenarea


*   Axa 0 este axa ordonatelor, iar axa 1 este axa abciselor.
*   Parametrii funcțiilor sunt de tip **tuple**



In [ ]:
# Concatenarea
# Metoda concatenate
A_conc_vert1 = np.concatenate((A_mat, A_mat), axis=0)
print(A_conc_vert1)

A_conc_oriz1 = np.concatenate((A_mat, A_mat), axis=1)
print(A_conc_oriz1)

# Metodele vstack și hstack
A_conc_vert2 = np.vstack( (A_mat, A_mat) )
print(A_conc_vert2)

A_conc_oriz2 = np.hstack( (A_mat, A_mat) )
print(A_conc_oriz2)

[[ 2  4  0]
 [ 5  7 -2]
 [12  5 -4]
 [ 2  4  0]
 [ 5  7 -2]
 [12  5 -4]]
[[ 2  4  0  2  4  0]
 [ 5  7 -2  5  7 -2]
 [12  5 -4 12  5 -4]]
[[ 2  4  0]
 [ 5  7 -2]
 [12  5 -4]
 [ 2  4  0]
 [ 5  7 -2]
 [12  5 -4]]
[[ 2  4  0  2  4  0]
 [ 5  7 -2  5  7 -2]
 [12  5 -4 12  5 -4]]


## Generarea vectorilor folosind metoda **arange**

Generează vectori între două limite: [inferioară și superioară), folosind ca pas cel de-al treilea argument. 

In [ ]:
b_vec1 = np.arange(6)
print(b_vec1)

b_vec2 = np.arange(2, 10)
print(b_vec2)

b_vec3 = np.arange(15, 30, 2)
print(b_vec3)

[0 1 2 3 4 5]
[2 3 4 5 6 7 8 9]
[15 17 19 21 23 25 27 29]


## Funcțiile **linspace** și **logspace**

Funcționare similară cu a Matlab-ului. **Linspace** generează valori în progresie aritmetică între limitele menționate, iar **logspace** folosește aceste valori ca puteri ale lui 10. 

In [ ]:
# Funcția linspace
c_vec1 = np.linspace(0, 11, 5)
print(c_vec1)

c_vec2 = np.linspace(0, 4, 3)
print(c_vec2)

# Funcția logspace
c_vec3 = np.logspace(0, 4, 3)
print(c_vec3)

c_vec4 = 10**(np.linspace(0, 4, 3))
print(c_vec3 - c_vec4)

[ 0.    2.75  5.5   8.25 11.  ]
[0. 2. 4.]
[1.e+00 1.e+02 1.e+04]
[0. 0. 0.]


## Funcțiile **zeros** și **ones**


*   Dimensiunile sunt ca tip de date **tuple**
*   Dacă se folosește un singur argument, va genera un vector linie. (nu o matrice pătratică precum în Matlab)



In [ ]:
# Funcția zeros
B_mat1 = np.zeros(2)
print(B_mat1)

B_mat2 = np.zeros( (2,2) )
print(B_mat2)

# Funcția ones
B_mat3 = np.ones(5)
print(B_mat3)

B_mat4 = np.ones( (3,1) )
print(B_mat4)

[0. 0.]
[[0. 0.]
 [0. 0.]]
[1. 1. 1. 1. 1.]
[[1.]
 [1.]
 [1.]]


## Funcțiile **rand**, **randint** și **randn**

* Funcțiile sunt importate din NumPy, din modulul **random**. 
* Funcția **rand** generează un vector/o matrice cu valori aparținând distribuției uniforme.
* Funcția **randint** generează un vector/o matrice cu valori întregi incluse între un minim și un maxim. Dimensiunea este specificată sub formă de tuple.
* Funcția **randn** generează un vector/o matrice cu valori aparținând distribuției normale

In [ ]:
from numpy import random as rnd

# Funcția rand
d_vec1 = rnd.rand(4)
print(d_vec1)

d_vec2 = rnd.rand(2,4)
print(d_vec2)

d_vec3 = rnd.rand(3,2,3)
print(d_vec3)

# Funcția randint
d_vec4 = rnd.randint(2,3)
print(d_vec4)

C_mat1 = rnd.randint(0,10, (2,3))
print(C_mat1)

# Funcția randn
d_vec5 = rnd.randn(5,1)
print(d_vec5)

C_mat2 = rnd.randn(4,2)
print(C_mat2)

[0.6317357  0.52372902 0.77071056 0.43016075]
[[0.0847131  0.50887079 0.71166395 0.00514162]
 [0.98848512 0.82293269 0.77454527 0.90111707]]
[[[0.66203884 0.81012438 0.0927361 ]
  [0.08627272 0.15388703 0.04309684]]

 [[0.1641657  0.33900626 0.52503274]
  [0.38990634 0.2653384  0.92973844]]

 [[0.51608078 0.33229491 0.75744105]
  [0.13077202 0.49868895 0.34421425]]]
2
[[9 2 2]
 [1 0 5]]
[[ 0.65148847]
 [-0.10778442]
 [-0.24123542]
 [-2.12479486]
 [-0.94098605]]
[[-0.35793072 -0.85069382]
 [-0.05681811  1.18551033]
 [-0.52402813  1.3860196 ]
 [ 1.61780306  0.74731509]]


## Funcțiile **eye** și **identity**


*   Generează o matrice pătratică
*   Funcția **eye** este similară cu cea din Matlab, funcția **identity** generează doar matrici identitate pătratice.



In [ ]:
# Funcția eye
I1 = np.eye(3)
print(I1)

I2 = np.eye(3,4,1)
print(I2)

# Funcția identity
I3 = np.identity(3)
print(I3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Funcții și operatori specifici lucrului cu vectori și matrice

## Înmulțirea element cu element și înmulțirea matriceală

*   În Python/NumPy, operatorul de înmulțire produce o înmulțire element cu element în cazul vectorilor și matricelor
*   Înmulțirea maticeală se realizează folosind funcția **matmul**



In [ ]:
# Înmulțire element cu element
e_vec1 = rnd.randint(0,10, (1, 5))
e_vec2 = rnd.randint(0,10, (1, 5))

prod_ham = e_vec1 * e_vec2
print(prod_ham)

D_mat1 = rnd.randint(0,10, (3,3))
D_mat2 = rnd.randint(0,10, (3,3))

D_prod_ham = D_mat1 * D_mat2
print(D_prod_ham)

# Înmulțire matriceală
prod_vec_mat = np.matmul(e_vec1, np.transpose(e_vec2))
print(prod_vec_mat)

D_mat3 = rnd.randint(0,10, (3,2))
D_mat4 = rnd.randint(0,10, (2,3))
D_prod_mat = np.matmul(D_mat3, D_mat4)
print(D_prod_ham)

[[ 5 25 36  2 28]]
[[21  5  6]
 [36 32  9]
 [27 45  0]]
[[96]]
[[21  5  6]
 [36 32  9]
 [27 45  0]]


## Funcțiile **dot**, **transpose** și **conj**/**conjugate**


*   Funcția **dot** calculează produsul scalar al doi vectori sau produsul matriceal a două matrici (însă este de preferat utilizarea funcției **matmul**)



In [ ]:
# Funcția dot
f_vec1 = rnd.randn(5)
f_vec2 = rnd.randn(5)

dot_f = np.dot(f_vec1, f_vec2)
print(dot_f)

F_mat1 = rnd.rand(3,3)
F_mat2 = rnd.rand(3,3)

print(np.dot(F_mat1,F_mat2) - np.matmul(F_mat1, F_mat2))

# Funcția transpose
f2_trans = np.transpose(f_vec2)
print(np.matmul(f_vec1, f2_trans))

# Funcția conj/conjugate
f_vec3 = rnd.randn(3) + 1j*rnd.rand(3)
print(f_vec3)

f_vec3_conj = np.conj(f_vec3)
f_vec3_conjugate = np.conjugate(f_vec3)

print(f_vec3_conj, f_vec3_conjugate, sep="\n")

1.3497445635565182
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
1.3497445635565182
[-0.53196371+0.21660195j  0.51636589+0.73244843j  0.39423841+0.71233441j]
[-0.53196371-0.21660195j  0.51636589-0.73244843j  0.39423841-0.71233441j]
[-0.53196371-0.21660195j  0.51636589-0.73244843j  0.39423841-0.71233441j]


## Funcțiile **len**, **size** și variabila **shape**
 
*   Funcția **len** este o funcție specifică Python (nu NumPy) și afișează numărul de elemente al unei structuri de date (listă, tuplă, vector, etc.)
*   Variabila **shape** este o varibilă specifică NumPy care afișează dimensiunile datelor de tip array
*   Funcția **size** este o funcție specifică NumPy care returneză numărul elementelor din cadrul unui array



In [ ]:
# Funcția len
a_list = [2, 4, 5, 'pisică']
g_vec = np.array([2, -5, 3, 5, 2])

print(len(a_list), len(g_vec), sep="\n")

# Funcția shape
g_vec1 = rnd.randn(12)
print(g_vec1.shape)

g_vec2 = rnd.randn(12,1)
print(g_vec2.shape)

G_mat = rnd.randint(0,100, (2,4))
print(G_mat.shape)

# Funcția size
print(g_vec2.size)
print(G_mat.size)

4
5
(12,)
(12, 1)
(2, 4)
12
8


## Funcțiile **min** și **max**

*   Returnează elementele minime, respective maxime din cadrul unui vector sau unei matrice
*   Spre deosebire de Matlab, în cazul matricelor, nu se vor returna elementele minime/maxime pe fiecare coloană în parte



In [ ]:
# Funcția min
H_mat1 = np.array([[1, 3, 6], [-4, 3, -1]])
print(np.min(H_mat1))

# Funcția max
print(np.max(H_mat1))

-4
6


## Funcția **sort**

*   Sortează ascendent elementele din cadrul unui vector/unei matrice în funcție de axele selectate
*   Dacă nu se specifică nicio axă (None), va transforma matricea/vectorul într-un vector linie și va sorta elementele ascendent
*   Predifinit sortarea se va face pe ultima axă a tipului respectiv de date
*   Pentru a sorta elementele descendent se folosește împreună cu alte funcții/metode



In [ ]:
m_vec = np.array([[1,4],[3,1]])
print(m_vec)

# Sortare pe axa absciselor (ultima dintre axe în exemplul de față)
m_oriz = np.sort(m_vec)
print(m_oriz)

# Sortare pe axa ordonatelor
m_ver = np.sort(m_vec, axis=0)
print(m_ver)

# Transformarea în vector linie și sortarea elementelor
m_flat = np.sort(m_vec,axis=None)
print(m_flat)

# Sortarea descendentă a elementelor
# Funcția flip
print(np.flip(m_flat))

# Operatorul :
print(m_flat[::-1])

[[1 4]
 [3 1]]
[[1 4]
 [1 3]]
[[1 1]
 [3 4]]
[1 1 3 4]
[4 3 1 1]
[4 3 1 1]


## Funcția **where**
Returnează elemente din cadrul unui vector pe baza condiției/condițiilor. Este asemănătoare funcției **find*** din Matlab.



In [ ]:
n_vec = np.arange(5,20, 3)
print(n_vec)

n_vec1 = np.where(n_vec < 14)
print(n_vec1)

# Afișarea indicelor care îndeplinesc condiția
print(n_vec1[0])

n_vec2 = np.where( (n_vec < 14) | (n_vec>7) )
print(n_vec2)

n_vec3 = np.where(n_vec <12, n_vec, 2*n_vec)
print(n_vec3)

[ 5  8 11 14 17]
(array([0, 1, 2]),)
[0 1 2]
(array([0, 1, 2, 3, 4]),)
[ 5  8 11 28 34]


## Funcțiile **rot90**, **fliplr** și **flipud**
Aceste funcții sunt similare cu cele din Matlab.

In [ ]:
M_mat = rnd.randn(2,3)
print(M_mat)

# Funcția rot90
print( np.rot90(M_mat) )
print( np.rot90(M_mat, -1) )

# Funcția fliplr
print( np.fliplr(M_mat) )

# Funcția flipud
print( np.flipud(M_mat) )

## Funcțiile **det** și **inv**

Acestea au același rol ca în Matlab. Sunt importate din NumPy, modulul **linalg**.

In [ ]:
from numpy.linalg import det, inv

N_mat = rnd.randint(0,100, (3,3))

# Calculul determinantului
print(det(N_mat))

# Calculul inversei unei matrici
print(inv(N_mat))

print(np.matmul(N_mat, inv(N_mat)) - np.identity(N_mat.shape[0]))

# Funcția diag
Funcționează ca funcția din Matlab.

In [ ]:
# Funcția diag pentru un vector
p_vec = np.array([3, 4, -2])
p_vec_2 = p_vec[:2]

print(np.diag(p_vec))
print(np.diag(p_vec_2,1))

# Funcția diag pentru o matrice
P_mat = rnd.randint(0,100,(3,3))
print(P_mat)

print(np.diag(P_mat))
print(np.diag(P_mat,-1))

## Funcțiile **tril** și **triu**
Funcționează ca în Matlab.

In [ ]:
# Funcția tril
print(np.tril(P_mat))
print(np.tril(P_mat,-1))

# Funcția triu
print(np.triu(P_mat))
print(np.triu(P_mat,1))

## Funcția **reshape** 

*  Are același rol ca funcția din Matlab.
*  Primește ca argumente vectorul/matricea a cărui dimensiune se va modfica, noua dimensiune sub formă de tuple și ordinea preluării elementelor
*  Ordinea poate fi de tip "C" (limbajul de programare), astfel se preiau elementele pe linie sau de tip "F" (Fortran), astfel se preiau elementele pe coloană. Implicit ordinea este de tip "C".

In [ ]:
k_vec = np.array([1, -5, 0, 5, 12])
print(k_vec.shape)

k_vec_col = np.reshape(k_vec, (len(k_vec),1))
print(k_vec_col)

K_mat = rnd.randint(0,100, (3,4))
print(K_mat)

K_mat_43_C = np.reshape(K_mat, (4,3), order="C")
print(K_mat_43_C)

K_mat_43_F = np.reshape(K_mat, (4,3), order="F")
print(K_mat_43_F)

# Scrierea și citirea din fișiere folosind NumPy și SciPy


*   Scrierea (**savetxt**) și citirea (**loadtxt**) de fișiere .csv folosind NumPy
*   Scrierea și cititea de fișiera .mat (Matlab) folosind scipy.io



In [ ]:
L_mat = rnd.randint(0,100,(3,4))
print(L_mat)

# Scrierea într-un fișier .csv
np.savetxt("out.csv", L_mat, delimiter=",")

# Citirea dintr-un fișier .csv
L_mat_read = np.loadtxt("out.csv", delimiter=",")
print(L_mat_read)


m_flat = np.sort(L_mat_read,axis=None)

import scipy.io as sio

# Scrierea în fișiere .mat
sio.savemat("out.mat", {"L_mat":m_flat})

L_mat_mat = sio.loadmat("out.mat")
print(L_mat_mat)
print(L_mat_mat["L_mat"])

# Exerciții

1. Generați aleator un vector cu 100 de elemente ce conține numere întregi cuprinse între 40 și 120. Salvați într-o variabila P_vec.mat pozițiile pe care elementele au valori cuprinse între 50 și 70.
2. Pornind de la vectorul a_vec = [2, 4, -5, 7, 18, 0], folosind o singură linie de comandă generați un vector care conține aceleași valori, dar în ordine inversă.
3. Generați aleator un vector ce conține numere întregi. Extrageți folosind o singură linie de comandă elementele de pe pozițiile impare.
4. Generați aleator o matrice 10x10. Folosind o singură comandă extrageți o matrice de dimensiuni 5x5 ce să conțină elementele din partea dreaptă jos a matricei inițiale.
5. Pornind de la vectorul c_vec = [8 9 7 4 5 2 6 5 4 1 3 9 8 7 5 2 3]. Generați un vector care să conțină toate elementele vectorului c_vec cuprinse între 2 și 5.
6. Scrieți o funcție în Python care primește o matrice pătratică ca parametru de intrare și returnează un vector ce conține elementele de pe diagonala secundară, matricea triunghiulară superioara și matricea triunghiulară inferioară.
7. Pornind de la următorii vectori: A = [8 9 10 11], B = [5], C = [9 8 5], generați o matrice care va conține pe rândurile ei acești vector. Vectori vor fi aliniați la dreapta în cadrul matricei, iar pentru ca dimensiunea lor să corespundă se vor adaugă valori de 0 începând cu coloana din stânga a matricei.
8. Generați folosind cât mai puține secvențe de cod următoare matrice A = [ 1 2 3 4 5 6 7;9 7 5 3 1 −1 −3;4 8 16 32 64 128 256].
